Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/tech_investement/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/tech_investement/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/tech_investement/settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /assets/FAXD.gif
Not Found: /dashboard/images/demo/pic2.jpg
Not Found: /dashboard/images/demo/pic3.jpg
Not Found: /dashboard/images/demo/pic1.jpg
Not Found: /dashboard/images/demo/pic4.jpg
Not Found: /dashboard/images/demo/pic6.jpg
Not Found: /dashboard/images/demo/pic7.jpg
Not Found: /dashboard/images/demo/pic5.jpg
Not Found: /dashboard/images/demo/pic8.jpg
Not Found: /favicon.ico
Not Found: /assets/FAXD.gif
Not Found: /dashboard/images/demo/pic1.jpg
Not Found: /dashboard/images/demo/pic4.jpg
Not Found: /dashboard/images/demo/pic2.jpg
Not Found: /dashboard/images/demo/pic3.jpg
Not Found: /dashboard/images/demo/pic7.jpg
Not Found: /dashboard/images/demo/pic6.jpg
Not Found: /dashboard/images/demo/pic5.jpg
Not Found: /dashboard/images/demo/pic8.jpg
/home/peekay/Documents/projects/django/deploy/techV2/investor/models.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/models.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /assets/FAXD.gif
Not Found: /dashboard/images/demo/pic1.jpg
Not Found: /dashboard/images/demo/pic2.jpg
Not Found: /dashboard/images/demo/pic3.jpg
Not Found: /dashboard/images/demo/pic5.jpg
Not Found: /dashboard/images/demo/pic6.jpg
Not Found: /dashboard/images/demo/pic4.jpg
Not Found: /dashboard/images/demo/pic7.jpg
Not Found: /dashboard/images/demo/pic8.jpg
Not Found: /favicon.ico
Not Found: /assets/FAXD.gif
Not Found: /dashboard/images/demo/pic1.jpg
Not Found: /dashboard/images/demo/pic5.jpg
Not Found: /dashboard/images/demo/pic4.jpg
Not Found: /dashboard/images/demo/pic2.jpg
Not Found: /dashboard/images/demo/pic3.jpg
Not Found: /dashboard/images/demo/pic8.jpg
Not Found: /dashboard/images/demo/pic6.jpg
Not Found: /dashboard/images/demo/pic7.jpg
Not Found: /favicon.ico
Not Found: /assets/FAXD.gif
Not Found: /dashboard/images/demo/pic1.jpg
Not Found: /dashboard/images/demo/pic2.jpg
Not Found: /dashboard/images/demo/pic4.jpg
Not Found: /dashboard/images/demo/pic3.jpg
Not Found: /dashboard/images/demo/pic6.jpg
Not Found: /dashboard/images/demo/pic5.jpg
Not Found: /dashboard/images/demo/pic7.jpg
Not Found: /dashboard/images/demo/pic8.jpg
Not Found: /favicon.ico
/home/peekay/Documents/projects/django/deploy/techV2/investor/models.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 776, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 750, in get_access_token
    print(r.text.encode('utf8')['access_token'])
TypeError: byte indices must be integers or slices, not str
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /assets/FAXD.gif
Not Found: /dashboard/images/demo/pic1.jpg
Not Found: /dashboard/images/demo/pic2.jpg
Not Found: /dashboard/images/demo/pic3.jpg
Not Found: /dashboard/images/demo/pic4.jpg
Not Found: /dashboard/images/demo/pic6.jpg
Not Found: /dashboard/images/demo/pic5.jpg
Not Found: /dashboard/images/demo/pic7.jpg
Not Found: /dashboard/images/demo/pic8.jpg
/home/peekay/Documents/projects/django/deploy/techV2/investor/models.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 776, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 750, in get_access_token
    print(r.text.encode('utf8').access_token)
AttributeError: 'bytes' object has no attribute 'access_token'
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 776, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 750, in get_access_token
    print(r.text.encode('utf8')["access_token"])
TypeError: byte indices must be integers or slices, not str
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 777, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 751, in get_access_token
    print(r.get("access_token"))
AttributeError: 'Response' object has no attribute 'get'
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 785, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 751, in get_access_token
    if response.status_code == 200:
NameError: name 'response' is not defined
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 784, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 755, in get_access_token
    access_token = r.get("access_token")
AttributeError: 'Response' object has no attribute 'get'
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 784, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 755, in get_access_token
    access_token = r.get("access_token")
AttributeError: 'Response' object has no attribute 'get'
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 783, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 751, in get_access_token
    if response.status_code == 200:
NameError: name 'response' is not defined
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 783, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 751, in get_access_token
    if response.status_code == 200:
NameError: name 'response' is not defined
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stkpush
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 783, in init_stk
    access_token = get_access_token()
  File "/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py", line 753, in get_access_token
    data = response.json()
NameError: name 'response' is not defined
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/tech_investement/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/tech_investement/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/models.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/models.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/models.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/models.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/views.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /check-payment-status
Not Found: /assets/FAXD.gif
Not Found: /dashboard/images/demo/pic2.jpg
Not Found: /dashboard/images/demo/pic6.jpg
Not Found: /dashboard/images/demo/pic5.jpg
Not Found: /dashboard/images/demo/pic1.jpg
Not Found: /dashboard/images/demo/pic3.jpg
Not Found: /dashboard/images/demo/pic4.jpg
Not Found: /dashboard/images/demo/pic7.jpg
Not Found: /dashboard/images/demo/pic8.jpg
Not Found: /assets/FAXD.gif
Not Found: /dashboard/images/demo/pic1.jpg
Not Found: /dashboard/images/demo/pic4.jpg
Not Found: /dashboard/images/demo/pic2.jpg
Not Found: /dashboard/images/demo/pic3.jpg
Not Found: /dashboard/images/demo/pic6.jpg
Not Found: /dashboard/images/demo/pic5.jpg
Not Found: /dashboard/images/demo/pic7.jpg
Not Found: /dashboard/images/demo/pic8.jpg
/home/peekay/Documents/projects/django/deploy/techV2/investor/admin.py changed, reloading.
Watching for file changes with StatReloader
/home/peekay/Documents/projects/django/deploy/techV2/investor/admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/investor/mpesapayment/
Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "investor_mpesapayment" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "investor_mpesapayment"
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 123, in __init__
    self.get_results(request)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 279, in get_results
    result_count = paginator.count
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/peekay/Documents/projects/django/deploy/techV2/techv2-venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "investor_mpesapayment" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "investor_mpesapayment"
                                          ^

Watching for file changes with StatReloader
Watching for file changes with StatReloader
